### ISSUE TITLE
运行gocks,遇错

### ISSUE THREAD

**Issue by luckypoem** [sipt/gocks#1]
hi.

yudeMacBook-Air:~ brite$ gocks
[ERROR] Fail to read file: open .conf/sipt.ini: no such file or directory
yudeMacBook-Air:~ brite$ 

怎么解决？
能否在此贴出sipt.ini的内容？

**Comment by sipt** [comment]
@luckypoem 示例配置文件没有上传上去，如果需要我可以补传一下。这个是老项目，可以转去新项目https://github.com/sipt/shuttle

**Comment by luckypoem** [comment]
麻烦补传一下sipt.ini
谢谢

**Comment by sipt** [comment]
https://github.com/sipt/gocks/blob/master/.conf/sipt.ini

**Comment by luckypoem** [comment]
hi.

运行gocks后，提示：
[INFO] load [General] success
[INFO] load [Proxy] success
[INFO] load [Proxy Group] success
[INFO] load [Host] success
[INFO] load [Rule] success
start listen: 8890

我设置浏览器的http代理服务器为127.0.0.1:8890,浏览器能成功翻墙。
但是如果设置浏览器的socks5代理服务器为127.0.0.1:8891,浏览器翻墙失败。说明sipt.ini里的socks-port = 8891根本没起作用。
如何解决这问题？
